obj-y	+=  oppo_project/
obj-y	+=  oppo_devinfo/
obj-y	+=  force_dump/
obj-y   +=  oppo_als_cali_value/
obj-y	+=  oppo_sensorinfo/
obj-y	+=  oppo_gpio/
obj-$(CONFIG_OPPO_HYPNUS)     +=  oppo_hypnus/

#ifdef VENDOR_EDIT
obj-$(CONFIG_OPPO_SHUTDOWN_DETECT)	+=  oppo_shutdown_detect/
#endif /* VENDOR_EDIT */
obj-$(CONFIG_OPPO_PHOENIX)     +=  oppo_phoenix/

#ifdef VENDOR_EDIT
obj-y     +=  oppo_healthinfo/
#endif /* VENDOR_EDIT */

#ifdef VENDOR_EDIT
#obj-$(CONFIG_RECORD_MDMRST)     +=  oppo_mdmrst/
obj-y     +=  oppo_mdmrst/
#endif /* VENDOR_EDIT */

#ifdefine VENDOR_EDIT
obj-y +=  oppo_kevent_feedback/
#endif /* VENDOR_EDIT */
